### ISSUE TITLE
Normalise object union, intersection and disjoint union 

### ISSUE THREAD

**Issue by iamcrowd** [iamcrowd/metamodel-api-OWL2import#27]
- Object Union (A,B), C should be A then C and B then C

- A, Intersection(B, C)  should be A then B and A then C

- A, DisjointUnion(B,C) should be A equiv B or C and B not C

**Comment by giuliano-marinelli** [comment]
Added at https://github.com/iamcrowd/metamodel-api-OWL2import/commit/ad7ab255fe9703db21573ae7a5137a165c4ac1d8
