### ISSUE TITLE
Relationships metric should consider only binary relationships, not counting subsumptions

### ISSUE THREAD

**Issue by iamcrowd** [iamcrowd/metamodel-api-OWL2import#30]
Currently, the #relationships metric is counting both the binary relationships and the subsumptions. We should only count binary relationships because we already count subsumptions with the respective metric

**Comment by giuliano-marinelli** [comment]
done at https://github.com/iamcrowd/metamodel-api-OWL2import/commit/ffc2fbb5d4ad1053a5d95c10fbdd6ba18b17d335
